# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170729_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
