# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_course_last_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': (('can_see_poll_admin', 'Can see the poll administration'), ('can_edit_poll', 'Can edit the poll'))},
        ),
    ]
