# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='open_enrollment',
            field=models.BooleanField(default=False),
        ),
    ]
