# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_remove_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='immediate_solutions',
            field=models.BooleanField(default=True),
        ),
    ]
